steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/orders-microservice -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/orders-microservice',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/750712810998/secrets/orders_database_url/versions/1
      env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY
